/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AverageGame {
  export type AverageGameInstanceStruct = {
    id: BigNumberish;
    name: string;
    entryPrice: BigNumberish;
    totalPlayers: BigNumberish;
    maxPlayers: BigNumberish;
    contractAddress: AddressLike;
    collateral: BigNumberish;
    gameFee: BigNumberish;
    players: AddressLike[];
    gameState: BigNumberish;
    gameMaster: AddressLike;
    winner: AddressLike;
    rewardClaimed: boolean;
    feeClaimed: boolean;
  };

  export type AverageGameInstanceStructOutput = [
    id: bigint,
    name: string,
    entryPrice: bigint,
    totalPlayers: bigint,
    maxPlayers: bigint,
    contractAddress: string,
    collateral: bigint,
    gameFee: bigint,
    players: string[],
    gameState: bigint,
    gameMaster: string,
    winner: string,
    rewardClaimed: boolean,
    feeClaimed: boolean
  ] & {
    id: bigint;
    name: string;
    entryPrice: bigint;
    totalPlayers: bigint;
    maxPlayers: bigint;
    contractAddress: string;
    collateral: bigint;
    gameFee: bigint;
    players: string[];
    gameState: bigint;
    gameMaster: string;
    winner: string;
    rewardClaimed: boolean;
    feeClaimed: boolean;
  };
}

export interface AverageGameModule_AverageGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "betAmount"
      | "blockNumber"
      | "collateralAmount"
      | "endGame"
      | "feeClaimed"
      | "gameFee"
      | "gameMaster"
      | "getAverageGameInstance"
      | "getBalance"
      | "getPlayerRevealedState"
      | "getPlayers"
      | "getPotentialWinners"
      | "id"
      | "initGame"
      | "joinGame"
      | "maxGuess"
      | "maxPlayers"
      | "minGuess"
      | "name"
      | "potentialWinners"
      | "requestRefund"
      | "revealGuess"
      | "rewardClaimed"
      | "startRevealPhase"
      | "state"
      | "timeToPass"
      | "totalBetAmount"
      | "totalCollateralAmount"
      | "totalPlayers"
      | "winner"
      | "withdrawGameFees"
      | "withdrawPricepool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BettingRoundClosed"
      | "CollateralDeposited"
      | "FeeCollected"
      | "GameCreated"
      | "GameEnded"
      | "PlayerJoined"
      | "PlayerRefunded"
      | "PlayerRevealedGuess"
      | "PrizeAwarded"
      | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(functionFragment: "betAmount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "blockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "endGame", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gameFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gameMaster",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAverageGameInstance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerRevealedState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPotentialWinners",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "id", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initGame",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "joinGame", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "maxGuess", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "minGuess", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "potentialWinners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealGuess",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardClaimed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startRevealPhase",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timeToPass",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBetAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollateralAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawGameFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPricepool",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "betAmount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gameFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gameMaster", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAverageGameInstance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerRevealedState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPotentialWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "id", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxGuess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxPlayers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minGuess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "potentialWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealGuess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startRevealPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timeToPass", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCollateralAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawGameFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPricepool",
    data: BytesLike
  ): Result;
}

export namespace BettingRoundClosedEvent {
  export type InputTuple = [gameId: BigNumberish];
  export type OutputTuple = [gameId: bigint];
  export interface OutputObject {
    gameId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralDepositedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCreatedEvent {
  export type InputTuple = [gameId: BigNumberish];
  export type OutputTuple = [gameId: bigint];
  export interface OutputObject {
    gameId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameEndedEvent {
  export type InputTuple = [gameId: BigNumberish];
  export type OutputTuple = [gameId: bigint];
  export interface OutputObject {
    gameId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    totalPlayersAmount: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    totalPlayersAmount: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    totalPlayersAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerRefundedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerRevealedGuessEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    guess: BigNumberish,
    salt: string,
    revealState: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    guess: bigint,
    salt: string,
    revealState: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    guess: bigint;
    salt: string;
    revealState: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeAwardedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish,
    guess: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    amount: bigint,
    guess: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    amount: bigint;
    guess: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, winner: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AverageGameModule_AverageGame extends BaseContract {
  connect(runner?: ContractRunner | null): AverageGameModule_AverageGame;
  waitForDeployment(): Promise<this>;

  interface: AverageGameModule_AverageGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  betAmount: TypedContractMethod<[], [bigint], "view">;

  blockNumber: TypedContractMethod<[], [bigint], "view">;

  collateralAmount: TypedContractMethod<[], [bigint], "view">;

  endGame: TypedContractMethod<[], [void], "nonpayable">;

  feeClaimed: TypedContractMethod<[], [boolean], "view">;

  gameFee: TypedContractMethod<[], [bigint], "view">;

  gameMaster: TypedContractMethod<[], [string], "view">;

  getAverageGameInstance: TypedContractMethod<
    [],
    [AverageGame.AverageGameInstanceStructOutput],
    "view"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getPlayerRevealedState: TypedContractMethod<
    [_player: AddressLike],
    [bigint],
    "view"
  >;

  getPlayers: TypedContractMethod<[], [string[]], "view">;

  getPotentialWinners: TypedContractMethod<[], [string[]], "view">;

  id: TypedContractMethod<[], [bigint], "view">;

  initGame: TypedContractMethod<
    [
      _gameId: BigNumberish,
      _name: string,
      _minGuess: BigNumberish,
      _maxGuess: BigNumberish,
      _maxPlayers: BigNumberish,
      _betAmount: BigNumberish,
      _gameMaster: AddressLike,
      _gameFee: BigNumberish
    ],
    [void],
    "payable"
  >;

  joinGame: TypedContractMethod<[_guess: BytesLike], [void], "payable">;

  maxGuess: TypedContractMethod<[], [bigint], "view">;

  maxPlayers: TypedContractMethod<[], [bigint], "view">;

  minGuess: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  potentialWinners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  requestRefund: TypedContractMethod<[], [void], "nonpayable">;

  revealGuess: TypedContractMethod<
    [_guess: BigNumberish, _salt: string],
    [void],
    "nonpayable"
  >;

  rewardClaimed: TypedContractMethod<[], [boolean], "view">;

  startRevealPhase: TypedContractMethod<[], [void], "nonpayable">;

  state: TypedContractMethod<[], [bigint], "view">;

  timeToPass: TypedContractMethod<[], [bigint], "view">;

  totalBetAmount: TypedContractMethod<[], [bigint], "view">;

  totalCollateralAmount: TypedContractMethod<[], [bigint], "view">;

  totalPlayers: TypedContractMethod<[], [bigint], "view">;

  winner: TypedContractMethod<[], [string], "view">;

  withdrawGameFees: TypedContractMethod<[], [void], "nonpayable">;

  withdrawPricepool: TypedContractMethod<
    [_winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "betAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blockNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "collateralAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "endGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeClaimed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "gameFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gameMaster"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAverageGameInstance"
  ): TypedContractMethod<
    [],
    [AverageGame.AverageGameInstanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerRevealedState"
  ): TypedContractMethod<[_player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPotentialWinners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(nameOrSignature: "id"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initGame"
  ): TypedContractMethod<
    [
      _gameId: BigNumberish,
      _name: string,
      _minGuess: BigNumberish,
      _maxGuess: BigNumberish,
      _maxPlayers: BigNumberish,
      _betAmount: BigNumberish,
      _gameMaster: AddressLike,
      _gameFee: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<[_guess: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "maxGuess"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxPlayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minGuess"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "potentialWinners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "requestRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealGuess"
  ): TypedContractMethod<
    [_guess: BigNumberish, _salt: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardClaimed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "startRevealPhase"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "timeToPass"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalBetAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCollateralAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPlayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "winner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawGameFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPricepool"
  ): TypedContractMethod<[_winner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BettingRoundClosed"
  ): TypedContractEvent<
    BettingRoundClosedEvent.InputTuple,
    BettingRoundClosedEvent.OutputTuple,
    BettingRoundClosedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralDeposited"
  ): TypedContractEvent<
    CollateralDepositedEvent.InputTuple,
    CollateralDepositedEvent.OutputTuple,
    CollateralDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameEnded"
  ): TypedContractEvent<
    GameEndedEvent.InputTuple,
    GameEndedEvent.OutputTuple,
    GameEndedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerRefunded"
  ): TypedContractEvent<
    PlayerRefundedEvent.InputTuple,
    PlayerRefundedEvent.OutputTuple,
    PlayerRefundedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerRevealedGuess"
  ): TypedContractEvent<
    PlayerRevealedGuessEvent.InputTuple,
    PlayerRevealedGuessEvent.OutputTuple,
    PlayerRevealedGuessEvent.OutputObject
  >;
  getEvent(
    key: "PrizeAwarded"
  ): TypedContractEvent<
    PrizeAwardedEvent.InputTuple,
    PrizeAwardedEvent.OutputTuple,
    PrizeAwardedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "BettingRoundClosed(uint256)": TypedContractEvent<
      BettingRoundClosedEvent.InputTuple,
      BettingRoundClosedEvent.OutputTuple,
      BettingRoundClosedEvent.OutputObject
    >;
    BettingRoundClosed: TypedContractEvent<
      BettingRoundClosedEvent.InputTuple,
      BettingRoundClosedEvent.OutputTuple,
      BettingRoundClosedEvent.OutputObject
    >;

    "CollateralDeposited(uint256,address,uint256)": TypedContractEvent<
      CollateralDepositedEvent.InputTuple,
      CollateralDepositedEvent.OutputTuple,
      CollateralDepositedEvent.OutputObject
    >;
    CollateralDeposited: TypedContractEvent<
      CollateralDepositedEvent.InputTuple,
      CollateralDepositedEvent.OutputTuple,
      CollateralDepositedEvent.OutputObject
    >;

    "FeeCollected(uint256,address,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "GameCreated(uint256)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameEnded(uint256)": TypedContractEvent<
      GameEndedEvent.InputTuple,
      GameEndedEvent.OutputTuple,
      GameEndedEvent.OutputObject
    >;
    GameEnded: TypedContractEvent<
      GameEndedEvent.InputTuple,
      GameEndedEvent.OutputTuple,
      GameEndedEvent.OutputObject
    >;

    "PlayerJoined(uint256,address,uint256)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

    "PlayerRefunded(uint256,address,uint256)": TypedContractEvent<
      PlayerRefundedEvent.InputTuple,
      PlayerRefundedEvent.OutputTuple,
      PlayerRefundedEvent.OutputObject
    >;
    PlayerRefunded: TypedContractEvent<
      PlayerRefundedEvent.InputTuple,
      PlayerRefundedEvent.OutputTuple,
      PlayerRefundedEvent.OutputObject
    >;

    "PlayerRevealedGuess(uint256,address,uint256,string,uint8)": TypedContractEvent<
      PlayerRevealedGuessEvent.InputTuple,
      PlayerRevealedGuessEvent.OutputTuple,
      PlayerRevealedGuessEvent.OutputObject
    >;
    PlayerRevealedGuess: TypedContractEvent<
      PlayerRevealedGuessEvent.InputTuple,
      PlayerRevealedGuessEvent.OutputTuple,
      PlayerRevealedGuessEvent.OutputObject
    >;

    "PrizeAwarded(uint256,address,uint256,uint256)": TypedContractEvent<
      PrizeAwardedEvent.InputTuple,
      PrizeAwardedEvent.OutputTuple,
      PrizeAwardedEvent.OutputObject
    >;
    PrizeAwarded: TypedContractEvent<
      PrizeAwardedEvent.InputTuple,
      PrizeAwardedEvent.OutputTuple,
      PrizeAwardedEvent.OutputObject
    >;

    "WinnerSelected(uint256,address,uint256)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
