/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AverageGameModule_AverageGame } from "./AverageGameModule_AverageGame";
export type { AverageGameModule_AverageGameFactory } from "./AverageGameModule_AverageGameFactory";
export * as factories from "./factories";
export { AverageGameModule_AverageGame__factory } from "./factories/AverageGameModule_AverageGame__factory";
export { AverageGameModule_AverageGameFactory__factory } from "./factories/AverageGameModule_AverageGameFactory__factory";
