/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chain11155111 from "./chain-11155111";
export type { chain11155111 };
import type * as chain31337 from "./chain-31337";
export type { chain31337 };
export * as factories from "./factories";
export type { AverageGameModule_AverageGame } from "./chain-11155111/artifacts/AverageGameModule_AverageGame";
export { AverageGameModule_AverageGame__factory } from "./factories/chain-11155111/artifacts/AverageGameModule_AverageGame__factory";
export type { AverageGameModule_AverageGameFactory } from "./chain-11155111/artifacts/AverageGameModule_AverageGameFactory";
export { AverageGameModule_AverageGameFactory__factory } from "./factories/chain-11155111/artifacts/AverageGameModule_AverageGameFactory__factory";
