/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AverageGameModule_AverageGame } from "./AverageGameModule_AverageGame";
export type { AverageGameModule_AverageGameFactory } from "./AverageGameModule_AverageGameFactory";
