/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AverageGameModule_AverageGame__factory } from "./AverageGameModule_AverageGame__factory";
export { AverageGameModule_AverageGameFactory__factory } from "./AverageGameModule_AverageGameFactory__factory";
